const ERROR_CODES = Object.freeze({
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_ACCOUNT_INACTIVE: "AUTH_ACCOUNT_INACTIVE",
  AUTH_PASSWORD_MISMATCH: "AUTH_PASSWORD_MISMATCH",
  AUTH_INVALID_OTP: "AUTH_INVALID_OTP",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_OTP_NOT_VERIFIED: "AUTH_OTP_NOT_VERIFIED",
  AUTH_OTP_ATTEMPT_LIMIT_EXCEEDED: "AUTH_OTP_ATTEMPT_LIMIT_EXCEEDED",
  AUTH_OTP_RESEND_TOO_SOON: "AUTH_OTP_RESEND_TOO_SOON",
  AUTH_PASSWORD_CHANGE_REQUIRED: "AUTH_PASSWORD_CHANGE_REQUIRED",
  AUTH_USER_ALREADY_EXISTS: "AUTH_USER_ALREADY_EXISTS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_EMPLOYEE_EMAIL_MISMATCH: "AUTH_EMPLOYEE_EMAIL_MISMATCH",
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});

module.exports = ERROR_CODES;
