-- AlterTable
ALTER TABLE `maintenance_requests` ADD COLUMN `type` ENUM('INCIDENT', 'MAINTENANCE', 'NEW_ALLOCATION', 'EXCHANGE', 'RECALL', 'SOFTWARE_INSTALL', 'ACCESS_GRANT', 'OTHER') NOT NULL DEFAULT 'MAINTENANCE',
    MODIFY `asset_id` CHAR(36) NULL;
